title: Xaleth
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  All adventures must begin somewhere...
# baseurl: /docs # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
url: bilodeaujamiea.github.io # the base hostname and protocol for your site, e.g. 
# twitter_username: jekyllrb
github_username:  BilodeauJamieA

# Build settings
theme: just-the-docs

exclude:
  - DM_Stuff